/** Product copy for the routine editor (es-AR). */

export const ROUTINE_COPY = {
  navRoutines: 'Rutinas',
  listTitle: 'Rutinas',
  listSubtitle: 'Plantillas del sistema y las que armes vos.',
  createCta: 'Nueva rutina',
  manageCta: 'Gestionar rutinas',
  emptyTitle: 'No hay rutinas para mostrar',
  emptyBody: 'Todavía no hay plantillas visibles. Podés crear una rutina propia.',
  editCta: 'Editar',
  viewCta: 'Ver',
  deleteCta: 'Eliminar',
  systemBadge: 'Plantilla',
  ownBadge: 'Tuya',
  createTitle: 'Nueva rutina',
  editTitle: 'Editar rutina',
  viewTitle: 'Rutina',
  nameLabel: 'Nombre',
  descriptionLabel: 'Descripción',
  kindLabel: 'Tipo',
  kindGym: 'Gimnasio',
  kindHome: 'En casa',
  restLabel: 'Descanso entre series (segundos)',
  restHint: 'El API guarda el descanso a nivel rutina, no por ejercicio.',
  exercisesLegend: 'Ejercicios',
  addExercise: 'Agregar',
  addExerciseLabel: 'Agregar ejercicio',
  catalogLabel: 'Ejercicio del catálogo',
  emptyExercises: 'Agregá al menos un ejercicio a la rutina.',
  duplicateExercise: 'Ese ejercicio ya está en la lista.',
  moveUp: 'Subir',
  moveDown: 'Bajar',
  remove: 'Quitar',
  setsLabel: 'Series',
  repsLabel: 'Reps',
  saveCreate: 'Crear rutina',
  saveEdit: 'Guardar cambios',
  saving: 'Guardando…',
  cancel: 'Cancelar',
  backToList: 'Volver a rutinas',
  readOnlyBanner: 'Esta plantilla del sistema es de solo lectura. Podés usarla en una sesión, no editarla.',
  notFound: 'Rutina no encontrada',
  notFoundBody: 'No existe o no está disponible para tu cuenta.',
  errorLoad: 'No se pudo cargar la rutina.',
  errorCatalog: 'No se pudo cargar el catálogo de ejercicios.',
  errorGeneric: 'No se pudo guardar la rutina. Probá de nuevo.',
  errorUnauthorized: 'Tenés que iniciar sesión para continuar.',
  errorForbidden: 'No podés modificar una rutina del sistema.',
  errorValidation: 'Revisá los datos de la rutina.',
  errorName: 'El nombre debe tener al menos 2 caracteres.',
  errorEmptyExercises: 'La rutina necesita al menos un ejercicio.',
  errorSets: 'Las series tienen que ser 1 o más.',
  errorReps: 'Las repeticiones tienen que ser 1 o más.',
  errorRest: 'El descanso tiene que ser 0 o más segundos.',
  errorWriteUnavailable:
    'Todavía no está disponible el alta o edición de rutinas en el servidor. El formulario quedó listo; falta POST/PATCH /api/routines.',
  errorDeleteUnavailable: 'No se pudo eliminar la rutina.',
  deleteConfirm: '¿Eliminar esta rutina? Esta acción no se puede deshacer.',
  mediaEmpty: 'Sin imagen',
  videoEmpty: 'Sin video',
  seeVideo: 'Ver video',
  imageUrlLabel: 'URL de imagen',
  videoUrlLabel: 'URL de video',
  mediaUrlHint: 'Solo URLs https://. El servidor limita a 2048 caracteres; no hay subida de archivos.',
  mediaUrlLengthHint: 'La URL de media no puede superar 2048 caracteres.',
  uploadLabel: 'Subir archivo',
  uploadDisabled:
    'La subida de archivos no está disponible. Pegá una URL en los campos de media o esperá el endpoint de upload.',
  uploadTodo: 'TODO BE: no hay POST de upload de media; solo imageUrl/videoUrl en ejercicios propios.',
  systemMediaLocked: 'La media de un ejercicio del sistema no se puede cambiar.',
} as const;

export const ROUTINE_TEST_IDS = {
  list: 'routine-editor-list',
  listItem: 'routine-editor-card',
  createCta: 'routine-create-cta',
  manageCta: 'routine-manage-cta',
  form: 'routine-editor-form',
  name: 'routine-name-input',
  description: 'routine-description-input',
  rest: 'routine-rest-input',
  kindGym: 'routine-kind-gym',
  kindHome: 'routine-kind-home',
  catalog: 'routine-exercise-catalog',
  addExercise: 'routine-add-exercise',
  exerciseRow: 'routine-exercise-row',
  save: 'routine-save',
  delete: 'routine-delete',
  error: 'routine-editor-error',
  empty: 'routine-editor-empty',
  notFound: 'routine-not-found',
  readOnly: 'routine-readonly-banner',
  media: 'routine-exercise-media',
  video: 'routine-exercise-video',
  upload: 'routine-media-upload',
  imageUrl: 'routine-exercise-image-url',
  videoUrl: 'routine-exercise-video-url',
} as const;
