/** Product copy for the routine editor (es-AR). */

export const ROUTINE_COPY = {
  navRoutines: 'Rutinas',
  listTitle: 'Rutinas',
  listSubtitle: 'Plantillas del sistema y las que armes vos.',
  createCta: 'Crear manual',
  createCoachCta: '✦ Crear con Coach Atlas',
  manageCta: 'Gestionar rutinas',
  emptyTitle: 'No hay rutinas para mostrar',
  emptyBody: 'Todavía no hay plantillas visibles. Podés crear una rutina propia.',
  editCta: 'Editar',
  viewCta: 'Ver',
  deleteCta: 'Eliminar',
  systemBadge: 'Plantilla',
  ownBadge: 'Tuya',
  createTitle: 'Nueva rutina',
  editTitle: 'Editar rutina',
  viewTitle: 'Rutina',
  detailTitle: 'Detalle de Rutina',
  detailTab: '1. Detalle',
  constructorTab: '2. Constructor',
  coachTab: '3. Coach Atlas',
  coachUnavailable: 'Coach Atlas todavía no tiene una pantalla conectada para esta rutina.',
  detailEyebrowGym: 'Gimnasio',
  detailEyebrowHome: 'En casa',
  startWorkout: '▶ Iniciar este entrenamiento',
  startWorkoutBusy: 'Iniciando…',
  editRoutine: 'Editar rutina',
  exerciseSequenceTitle: 'Secuencia de ejercicios',
  exerciseSequenceHelp: 'Podés consultar técnica pulsando cada ejercicio cuando tenga indicaciones.',
  exerciseSequenceEmpty: 'Esta rutina todavía no tiene ejercicios cargados.',
  muscleEmphasis: 'Énfasis muscular',
  startError: 'No se pudo iniciar el entrenamiento. Probá de nuevo.',
  nameLabel: 'Nombre',
  descriptionLabel: 'Descripción',
  kindLabel: 'Tipo',
  kindGym: 'Gimnasio',
  kindHome: 'En casa',
  restLabel: 'Descanso entre series (segundos)',
  restHint: 'El API guarda el descanso a nivel rutina, no por ejercicio.',
  exercisesLegend: 'Ejercicios',
  addExercise: 'Agregar',
  addExerciseLabel: 'Agregar ejercicio',
  catalogLabel: 'Ejercicio del catálogo',
  emptyExercises: 'Agregá al menos un ejercicio a la rutina.',
  duplicateExercise: 'Ese ejercicio ya está en la lista.',
  moveUp: 'Subir',
  moveDown: 'Bajar',
  remove: 'Quitar',
  setsLabel: 'Series',
  repsLabel: 'Reps',
  saveCreate: 'Crear rutina',
  saveEdit: 'Guardar cambios',
  saving: 'Guardando…',
  cancel: 'Cancelar',
  backToList: 'Volver a rutinas',
  readOnlyBanner: 'Esta plantilla del sistema es de solo lectura. Podés usarla en una sesión, no editarla.',
  notFound: 'Rutina no encontrada',
  notFoundBody: 'No existe o no está disponible para tu cuenta.',
  errorLoad: 'No se pudo cargar la rutina.',
  errorCatalog: 'No se pudo cargar el catálogo de ejercicios.',
  errorGeneric: 'No se pudo guardar la rutina. Probá de nuevo.',
  errorUnauthorized: 'Tenés que iniciar sesión para continuar.',
  errorForbidden: 'No podés modificar una rutina del sistema.',
  errorValidation: 'Revisá los datos de la rutina.',
  errorName: 'El nombre debe tener al menos 2 caracteres.',
  errorEmptyExercises: 'La rutina necesita al menos un ejercicio.',
  errorSets: 'Las series tienen que ser 1 o más.',
  errorReps: 'Las repeticiones tienen que ser 1 o más.',
  errorRest: 'El descanso tiene que ser 0 o más segundos.',
  errorWriteUnavailable:
    'Todavía no está disponible el alta o edición de rutinas en el servidor. El formulario quedó listo; falta POST/PATCH /api/routines.',
  errorDeleteUnavailable: 'No se pudo eliminar la rutina.',
  deleteConfirm: '¿Eliminar esta rutina? Esta acción no se puede deshacer.',
  mediaEmpty: 'Sin imagen',
  videoEmpty: 'Sin video',
  seeVideo: 'Ver video',
  imageUrlLabel: 'URL de imagen',
  videoUrlLabel: 'URL de video',
  mediaUrlHint: 'Solo URLs https://. El servidor limita a 2048 caracteres. También podés subir un archivo en ejercicios propios.',
  mediaUrlLengthHint: 'La URL de media no puede superar 2048 caracteres.',
  uploadLabel: 'Subir archivo',
  uploadImageLabel: 'Subir imagen',
  uploadVideoLabel: 'Subir video',
  uploadHint:
    'Subida directa hasta 4 MB. Para videos grandes hace falta subida directa a Blob; si no está configurado, pegá una URL https://.',
  uploadDisabled: 'La media de este ejercicio no se puede cambiar. Pegá URLs solo en ejercicios propios.',
  uploadUploading: 'Subiendo archivo…',
  uploadSuccess: 'Archivo subido. Revisá la URL cargada antes de guardar.',
  uploadInvalidUrl: 'La subida devolvió una URL inválida. Probá pegando una URL https://.',
  uploadGenericError: 'No se pudo subir el archivo. Probá de nuevo o pegá una URL https://.',
  systemMediaLocked: 'La media de un ejercicio del sistema no se puede cambiar.',
} as const;

export const ROUTINE_TEST_IDS = {
  list: 'routine-editor-list',
  listItem: 'routine-editor-card',
  createCta: 'routine-create-cta',
  createCoachCta: 'routine-create-coach-cta',
  manageCta: 'routine-manage-cta',
  form: 'routine-editor-form',
  name: 'routine-name-input',
  description: 'routine-description-input',
  rest: 'routine-rest-input',
  kindGym: 'routine-kind-gym',
  kindHome: 'routine-kind-home',
  catalog: 'routine-exercise-catalog',
  addExercise: 'routine-add-exercise',
  exerciseRow: 'routine-exercise-row',
  save: 'routine-save',
  delete: 'routine-delete',
  error: 'routine-editor-error',
  empty: 'routine-editor-empty',
  notFound: 'routine-not-found',
  readOnly: 'routine-readonly-banner',
  media: 'routine-exercise-media',
  video: 'routine-exercise-video',
  upload: 'routine-media-upload',
  uploadImage: 'routine-media-upload-image',
  uploadVideo: 'routine-media-upload-video',
  imageUrl: 'routine-exercise-image-url',
  videoUrl: 'routine-exercise-video-url',
  detail: 'routine-detail',
  detailStart: 'routine-detail-start',
  detailSummary: 'routine-detail-summary',
  detailExercise: 'routine-detail-exercise',
} as const;
