/** Product copy for shell and base UI states (es-AR). */
export const UI_COPY = {
  brand: 'Atlas Fitness',
  brandShort: 'Atlas',
  skipToContent: 'Saltar al contenido',
  primaryNav: 'Principal',
  tabNav: 'Pestañas',
  navHome: 'Inicio',
  navToday: 'Hoy',
  navHistory: 'Historial',
  navSettings: 'Ajustes',
  navSession: 'Sesión',
  navTraining: 'Entrenar',
  navProgress: 'Progreso',
  navProfile: 'Perfil',
  notifications: 'Notificaciones',
  notificationsSoon: 'Notificaciones — próximamente',
  navLogin: 'Iniciar sesión',
  navRegister: 'Crear cuenta',
  logout: 'Cerrar sesión',
  loading: 'Cargando…',
  errorTitle: 'Algo salió mal',
  emptyWorkoutsTitle: 'Todavía no hay entrenos',
  emptyWorkoutsBody: 'No tienes entrenamientos registrados aún.',
  emptySetsTitle: 'Sin series',
  emptySetsBody: 'No hay series registradas aún.',
  startFirstWorkout: 'Iniciar tu primer entrenamiento',
  workoutNotFound: 'Entrenamiento no encontrado',
  continueWorkout: 'Continuar Entrenamiento',
  startWorkout: 'Empezar Entreno',
  greeting: (name: string) => `Hola, ${name}`,
  welcome: (name: string) => `Bienvenido, ${name}`,
  tipOfDay: 'Consejo del día',
  moodToday: '¿Cómo te sentís hoy?',
  emptyTipTitle: 'Sin consejo hoy',
  emptyTipBody: 'Podés entrenar igual y sumar a la racha.',
  progressTitle: 'Progreso',
  progressSubtitlePrefix: 'Datos reales al',
  progressPeriodAria: 'Rango de progreso',
  progressPeriodWeek: 'Semana',
  progressPeriodMonth: 'Mes',
  progressPeriodQuarter: '3 meses',
  progressError: 'No pudimos cargar tu progreso. Probá de nuevo en unos minutos.',
  progressSummaryTitle: 'Resumen',
  progressSessions: 'Sesiones',
  progressSessionSingular: 'sesión',
  progressSessionPlural: 'sesiones',
  progressCompletedSessionsLabel: 'Sesiones completadas',
  progressTotalTime: 'Tiempo total',
  progressTotalTimeLabel: 'Tiempo total',
  progressWeekTitle: 'Consistencia semanal',
  progressWeekBody: 'Días con entrenamiento terminado o check-in esta semana.',
  progressWeekActiveLabel: 'Días activos esta semana',
  progressWeekEmptyTitle: 'Sin consistencia semanal',
  progressWeekEmptyBody: 'Cuando haya datos reales de esta semana, Atlas los va a mostrar acá.',
  progressRecentSessionsTitle: 'Sesiones recientes',
  progressFreeWorkout: 'Entrenamiento libre',
  progressSessionDurationLabel: 'Duración de la sesión',
} as const;

export const UI_COPY_TEST_IDS = {
  appShell: 'app-shell',
  appHeader: 'app-header',
  appBottomNav: 'app-bottom-nav',
  notificationsButton: 'notifications-button',
  formError: 'form-error',
  homeLoginCta: 'home-login-cta',
  progressScreen: 'progress-screen',
} as const;
