/** Product copy for shell and base UI states (es-AR). */
export const UI_COPY = {
  brand: 'Atlas Fitness',
  brandShort: 'Atlas',
  skipToContent: 'Saltar al contenido',
  primaryNav: 'Principal',
  tabNav: 'Pestañas',
  navHome: 'Inicio',
  navToday: 'Hoy',
  navHistory: 'Historial',
  navSettings: 'Ajustes',
  navSession: 'Sesión',
  navTraining: 'Entrenar',
  navProgress: 'Progreso',
  navProfile: 'Perfil',
  profileTitle: 'Perfil',
  profileInitialsLabel: (name: string) => `Iniciales de ${name}`,
  profileAvatarFallback: 'AT',
  profileMiAtlasTitle: 'Mi Atlas',
  profileRoutinesTitle: 'Plan y rutinas',
  profileRoutinesDescription: 'Gestioná tus plantillas y el plan de entrenamiento.',
  profileHabitsTitle: 'Hábitos de bienestar',
  profileHabitsDescription: 'Registrá check-ins y seguí tus hábitos de hoy.',
  profileIntegrationsTitle: 'Integraciones',
  profileTelegramTitle: 'Telegram',
  profileTelegramExpiryPrefix: 'Vence:',
  profileApplicationTitle: 'Aplicación',
  profileUnitsTitle: 'Unidades de medida',
  profileUnitsDescription: 'Kilogramos (kg) · Métrico',
  profileAppearanceTitle: 'Apariencia',
  profileAppearanceDescription: 'Automático según el sistema',
  profileAccountTitle: 'Cuenta',
  profileLogoutDescription: 'Cerrá tu sesión en este dispositivo.',
  profileVersionLabel: (version: string) => `v${version}`,
  notifications: 'Notificaciones',
  notificationsSoon: 'Notificaciones — próximamente',
  navLogin: 'Iniciar sesión',
  navRegister: 'Crear cuenta',
  logout: 'Cerrar sesión',
  loading: 'Cargando…',
  errorTitle: 'Algo salió mal',
  emptyWorkoutsTitle: 'Todavía no hay entrenos',
  emptyWorkoutsBody: 'No tienes entrenamientos registrados aún.',
  emptySetsTitle: 'Sin series',
  emptySetsBody: 'No hay series registradas aún.',
  startFirstWorkout: 'Iniciar tu primer entrenamiento',
  workoutNotFound: 'Entrenamiento no encontrado',
  continueWorkout: 'Continuar Entrenamiento',
  startWorkout: 'Empezar Entreno',
  greeting: (name: string) => `Hola, ${name}`,
  welcome: (name: string) => `Bienvenido, ${name}`,
  tipOfDay: 'Consejo del día',
  moodToday: '¿Cómo te sentís hoy?',
  emptyTipTitle: 'Sin consejo hoy',
  emptyTipBody: 'Podés entrenar igual y sumar a la racha.',
  progressTitle: 'Progreso',
  progressSubtitlePrefix: 'Datos reales al',
  progressPeriodAria: 'Rango de progreso',
  progressPeriodWeek: 'Semana',
  progressPeriodMonth: 'Mes',
  progressPeriodQuarter: '3 meses',
  progressError: 'No pudimos cargar tu progreso. Probá de nuevo en unos minutos.',
  progressSummaryTitle: 'Resumen',
  progressSessions: 'Sesiones',
  progressSessionSingular: 'sesión',
  progressSessionPlural: 'sesiones',
  progressCompletedSessionsLabel: 'Sesiones completadas',
  progressTotalTime: 'Tiempo total',
  progressTotalTimeLabel: 'Tiempo total',
  progressWeekTitle: 'Consistencia semanal',
  progressWeekBody: 'Días con entrenamiento terminado o check-in esta semana.',
  progressWeekActiveLabel: 'Días activos esta semana',
  progressWeekEmptyTitle: 'Sin consistencia semanal',
  progressWeekEmptyBody: 'Cuando haya datos reales de esta semana, Atlas los va a mostrar acá.',
  progressRecentSessionsTitle: 'Sesiones recientes',
  progressFreeWorkout: 'Entrenamiento libre',
  progressSessionDurationLabel: 'Duración de la sesión',
  coachAdapt: {
    title: 'Adaptar entrenamiento',
    badge: 'Coach Atlas',
    subtitle: 'Ajustá la sesión con datos reales de tu check-in o el contexto que contás ahora.',
    baseSession: 'Sesión base',
    emptyTitle: 'Elegí un entrenamiento para adaptar',
    emptyBody: 'Entrá desde el plan de hoy para que Atlas sepa qué rutina revisar.',
    goTraining: 'Ir a Entrenar',
    startWithGuidance: 'Usar entrenamiento adaptado',
    keepOriginal: 'Mantener entrenamiento original',
    guidanceDisclosure: 'Se aplica solo a la sesión de hoy; tu rutina guardada no cambia.',
    adjustAgain: 'Ajustar otra cosa',
    starting: 'Iniciando…',
    confirmed: 'Entrenamiento confirmado. Te llevamos a la sesión guiada…',
  },
  training: {
    title: 'Entrenar',
    managePlan: 'Gestionar plan',
    todayEyebrow: 'Plan de hoy',
    startWorkout: 'Empezar entrenamiento',
    startingWorkout: 'Iniciando…',
    adaptWithCoach: 'Adaptar con Coach Atlas',
    viewDetails: 'Ver detalles',
    activeExists: 'Ya tenés una sesión activa. Continuá o finalizala antes de empezar otra.',
    continueGuided: 'Continuar sesión guiada',
    continueWorkout: 'Continuar entrenamiento',
    goalLabel: 'Objetivo',
    exerciseSingular: 'ejercicio',
    exercisePlural: 'ejercicios',
    setSingular: 'serie',
    setPlural: 'series',
    todayExerciseCountLabel: 'Ejercicios de la rutina de hoy',
    routineExerciseCountLabel: 'Ejercicios de la rutina',
    routineSetCountLabel: 'Series de la rutina',
    restTitle: 'Descanso programado',
    restBody: 'Tu plan marca pausa para hoy. Recuperá y volvé cuando toque entrenar.',
    noPlanTitle: 'Todavía no tenés un plan',
    noPlanBody: 'Creá una rutina o armá tu plan para que Atlas pueda mostrarte qué entrenar cada día.',
    createRoutine: 'Crear una rutina',
    missingRoutineTitle: 'La rutina programada ya no está disponible.',
    missingRoutineBody: 'Revisá tus rutinas o ajustá el plan antes de empezar.',
    newRoutineTitle: 'Nueva rutina',
    newRoutineBody: 'Elegí si Atlas te guía con IA o si preferís armarla manualmente.',
    createWithCoach: 'Crear rutina con Coach Atlas',
    createManually: 'Crear rutina manual',
    coachRoutine: {
      backToRoutines: 'Volver a rutinas',
      eyebrow: 'Coach Atlas',
      title: 'Crear rutina guiada',
      subtitle: 'Contale tu objetivo y Atlas propone un borrador usando solo ejercicios reales del catálogo.',
      loadingCatalog: 'Cargando catálogo de ejercicios…',
      catalogError: 'No pudimos cargar el catálogo de ejercicios.',
      emptyTitle: 'Catálogo vacío',
      emptyBody: 'No hay ejercicios disponibles para armar una rutina.',
      goalLabel: 'Objetivo',
      goalPlaceholder: 'Ej: ganar fuerza, entrenar en casa, volver después de una pausa…',
      daysLabel: 'Días por semana',
      locationLabel: 'Lugar',
      levelLabel: 'Nivel',
      gym: 'Gimnasio',
      home: 'Casa',
      beginner: 'Inicial',
      intermediate: 'Intermedio',
      advanced: 'Avanzado',
      generate: 'Generar propuesta',
      generating: 'Generando…',
      generateError: 'No pudimos generar la rutina. Probá de nuevo.',
      createError: 'No pudimos crear la rutina. Probá de nuevo.',
      fallbackBadge: 'Borrador determinístico',
      geminiBadge: 'Borrador con Gemini',
      proposalTitle: 'Propuesta Atlas',
      whyTitle: 'Por qué',
      daysMetric: 'Días por semana',
      exercisesMetric: 'Ejercicios propuestos',
      setsMetric: 'Series totales',
      aiSource: 'Sugerencia de Atlas',
      computedSource: 'Calculado por Atlas',
      exerciseBreakdownTitle: 'Detalle de ejercicios',
      accept: 'Crear esta rutina',
      adjustBrief: 'Ajustar el brief',
      creating: 'Creando rutina…',
    },
    myRoutinesTitle: 'Mis rutinas',
    emptyRoutinesTitle: 'Todavía no tenés rutinas',
    emptyRoutinesBody: 'Creá tu primera rutina para iniciar una sesión guiada desde acá.',
    routineStart: 'Iniciar',
    errorLoad: 'No se pudo cargar Entrenar. Probá de nuevo en unos minutos.',
  },
} as const;

export const UI_COPY_TEST_IDS = {
  appShell: 'app-shell',
  appHeader: 'app-header',
  appBottomNav: 'app-bottom-nav',
  notificationsButton: 'notifications-button',
  formError: 'form-error',
  homeLoginCta: 'home-login-cta',
  progressScreen: 'progress-screen',
} as const;
